id: I9DE44544
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T23:12:42.385266'
last_modified: '2022-05-30T23:12:42.385272'
parser: null
source_metadata:
  title: Shechen Kongtrul Series
  language: bo
  description: 'Texts by and about Pema Drimé Lekpé Lodrö (zhe chen kong sprul padma
    dri med legs pa''i blo gros, 1901-c.1960), the immediate reincarnation of Jamgön
    Kongtrul Lodrö Thaye at Shechen Monastery:'
  volume:
    fDEEE:
      title: Prayer to Shechen Kongtrul as Vajrasattva
      base_file: fDEEE.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
